project:
  name: "hierarchical_semantic_abstraction"
  seed: 42
  output_dir: "./outputs"
  save_dir: "./checkpoints"
  log_dir: "./logs"

data:
  dataset:
    train_path: "./data/train"
    val_path: "./data/val"
    test_path: "./data/test"
    image_size: 256
    batch_size: 32
    num_workers: 4
  augmentation:
    enable: true
    random_crop: true
    random_horizontal_flip: true
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1

model:
  clip:
    model_name: "ViT-B/32"
    freeze_encoder: true
  
  hierarchical_transformer:
    num_layers: 6
    num_heads: 8
    hidden_dim: 768
    ff_dim: 3072
    dropout: 0.1
    num_abstraction_levels: 4
    semantic_anchoring: true
    
  feature_decoder:
    initial_size: 32
    channels: [512, 256, 128, 64, 3]
    upsample_factor: 2
    use_residual: true

training:
  optimizer:
    type: "AdamW"
    learning_rate: 0.0001
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
  
  scheduler:
    type: "CosineAnnealingLR"
    T_max: 100
    eta_min: 0.000001
  
  training_params:
    num_epochs: 100
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
    precision: 16  # mixed precision training
  
  loss_weights:
    semantic: 1.0
    abstraction: 0.5
    consistency: 0.3

evaluation:
  metrics:
    clip_score: true
    bertscore: true
    lpips: true
    ssim: true
    perceptual_distance: true
    
  human_evaluation:
    num_samples: 100
    aspects: ["semantic_preservation", "abstraction_quality", "usefulness"]
    
  visualization:
    save_grid: true
    num_examples: 16
    save_individual: true

wandb:  # Weights & Biases configuration
  enable: true
  project: "hierarchical_semantic_abstraction"
  entity: null  # your wandb username/team
  tags: ["research", "hierarchical", "semantic-abstraction"]
  notes: "Initial training run"

debug:
  enable: false
  fast_dev_run: false
  overfit_batches: 0
  detect_anomaly: true
  profiler:
    enable: false
    profile_memory: true
    profile_cuda: true